// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mluP2y58zqxHHQrZCmK33TCDwWuu1yw',
    appId: '1:580150509683:web:4e68a4939d914475772a06',
    messagingSenderId: '580150509683',
    projectId: 'food-delivery-d7a7b',
    authDomain: 'food-delivery-d7a7b.firebaseapp.com',
    storageBucket: 'food-delivery-d7a7b.firebasestorage.app',
    measurementId: 'G-WWKJEVTFRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcK5HOiuerOVV4M2yQeRa6r66oLX7vx5Y',
    appId: '1:580150509683:android:220d0dc4a6be54b4772a06',
    messagingSenderId: '580150509683',
    projectId: 'food-delivery-d7a7b',
    storageBucket: 'food-delivery-d7a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmz2PCO_lIJthgu7Dni-xQkEWLlVtqQk',
    appId: '1:580150509683:ios:f44b0a37632db0b4772a06',
    messagingSenderId: '580150509683',
    projectId: 'food-delivery-d7a7b',
    storageBucket: 'food-delivery-d7a7b.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmz2PCO_lIJthgu7Dni-xQkEWLlVtqQk',
    appId: '1:580150509683:ios:f44b0a37632db0b4772a06',
    messagingSenderId: '580150509683',
    projectId: 'food-delivery-d7a7b',
    storageBucket: 'food-delivery-d7a7b.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
